openapi: 3.0.1
info:
  description: todo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Parent Template Plugin
  version: 1.0.0
servers:
- description: Plugin Endpoint URL
  url: https://jira.ru/rest/parent/1.0
paths:
  /transitions/getCurrentTransitions/{key}:
    get:
      operationId: getCurrentUser
      parameters:
      - in: path
        name: key
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            '*/*':
              schema:
                type: string
          description: default response
  /transitions/test/{key}:
    get:
      operationId: justTestParticipant
      parameters:
      - in: path
        name: key
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            '*/*':
              schema:
                type: string
          description: default response
