openapi: 3.0.1
info:
  description: todo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Parent Template Plugin
  version: "${project.version}"
servers:
- description: Plugin Endpoint URL
  url: https://jira.ru/rest/parent/1.0
